CREATE TABLE airline
(
    id          BIGINT       AUTO_INCREMENT PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    korean_name VARCHAR(100) NULL,
    code        VARCHAR(10)  NOT NULL,
    CONSTRAINT uk_airline_code UNIQUE (code)
);

INSERT INTO airline (name, korean_name, code)
VALUES
    ('12 North', NULL, '12'),
    ('1Time Airline', NULL, '1T'),
    ('40-Mile Air', NULL, 'Q5'),
    ('88', NULL, '47'),
    ('ABSA - Aerolinhas Brasileiras', NULL, 'M3'),
    ('ALAK', NULL, 'J4'),
    ('ATA Airlines (Iran)', NULL, 'I3'),
    ('ATRAN Cargo Airlines', NULL, 'V8'),
    ('Abacus International', NULL, '1B'),
    ('Abu Dhabi Amiri Flight', NULL, 'MO'),
    ('Access Air', NULL, 'ZA'),
    ('Ada Air', NULL, 'ZY'),
    ('Adam Air', NULL, 'KI'),
    ('Adria Airways', NULL, 'JP'),
    ('Aegean Airlines', '에게항공', 'A3'),
    ('Aer Arann', NULL, 'RE'),
    ('Aer Lingus', NULL, 'EI'),
    ('Aereonautica militare', NULL, 'JY'),
    ('Aero Benin', NULL, 'EM'),
    ('Aero Condor Peru', NULL, 'Q6'),
    ('Aero Contractors', NULL, 'AJ'),
    ('Aero Flight', NULL, 'GV'),
    ('Aero Lanka', NULL, 'QL'),
    ('Aero VIP (2D)', NULL, '2D'),
    ('Aero-Service', NULL, 'BF'),
    ('AeroMéxico', '아에로멕시코', 'AM'),
    ('AeroRep', NULL, 'P5'),
    ('AeroWorld', NULL, 'W4'),
    ('Aerocondor', NULL, '2B'),
    ('Aeroflot Russian Airlines', '아에로플로트', 'SU'),
    ('Aeroflot-Don', NULL, 'D9'),
    ('Aeroflot-Nord', NULL, '5N'),
    ('Aerolane', NULL, 'XL'),
    ('Aeroline GmbH', NULL, '7E'),
    ('Aerolineas Argentinas', NULL, 'AR'),
    ('Aerolineas Galapagos (Aerogal)', NULL, '2K'),
    ('Aerolitoral', NULL, '5D'),
    ('Aeromar', NULL, 'VW'),
    ('Aeropelican Air Services', NULL, 'OT'),
    ('Aeroper', NULL, 'PL'),
    ('Aerosur', NULL, '5L'),
    ('Aerosvit Airlines', NULL, 'VV'),
    ('Africa West', NULL, 'FK'),
    ('Afriqiyah Airways', NULL, '8U'),
    ('Aigle Azur', NULL, 'ZI'),
    ('Air Afrique', NULL, 'RK'),
    ('Air Algerie', NULL, 'AH'),
    ('Air Alps Aviation (A6)', NULL, 'A6'),
    ('Air Antilles Express', NULL, '3S'),
    ('Air Arabia', NULL, 'G9'),
    ('Air Arabia Egypt', NULL, 'E5'),
    ('Air Arabia Maroc', NULL, '3O'),
    ('Air Astana', NULL, 'KC'),
    ('Air Atlanta Icelandic', NULL, 'CC'),
    ('Air Austral', NULL, 'UU'),
    ('Air Bagan', NULL, 'W9'),
    ('Air Baltic', NULL, 'BT'),
    ('Air Bangladesh', NULL, 'B9'),
    ('Air Berlin', NULL, 'AB'),
    ('Air Bosna', NULL, 'JA'),
    ('Air Botswana', NULL, 'BP'),
    ('Air Bourbon', NULL, 'ZB'),
    ('Air Burkina', NULL, '2J'),
    ('Air Busan', '에어부산', 'BX'),
    ('Air Caledonie International', NULL, 'SB'),
    ('Air Canada', '캐나다항공', 'AC'),
    ('Air Canada Jazz', NULL, 'QK'),
    ('Air Caraïbes', NULL, 'TX'),
    ('Air Cargo Carriers', NULL, '2Q'),
    ('Air Cargo Germany', NULL, '6U'),
    ('Air Carnival', NULL, '2S'),
    ('Air Chathams', NULL, 'CV'),
    ('Air China', '중국국제항공', 'CA'),
    ('Air Choice One', NULL, '3E'),
    ('Air Comet Chile', NULL, '3I'),
    ('Air Costa', NULL, 'LB'),
    ('Air Dolomiti', NULL, 'EN'),
    ('Air Europa', NULL, 'UX'),
    ('Air Europe', NULL, 'PE'),
    ('Air Exel', NULL, 'XT'),
    ('Air Finland', NULL, 'OF'),
    ('Air Florida', NULL, 'QH'),
    ('Air Foyle', NULL, 'GS'),
    ('Air France', '에어프랑스', 'AF'),
    ('Air Glaciers', NULL, '7T'),
    ('Air Greenland', NULL, 'GL'),
    ('Air Guinee Express', NULL, '2U'),
    ('Air Guyane', NULL, 'GG'),
    ('Air Hamburg (AHO)', NULL, 'HH'),
    ('Air Iceland', NULL, 'NY'),
    ('Air India Express', NULL, 'IX'),
    ('Air India Limited', '에어인디아', 'AI'),
    ('Air India Regional', NULL, 'CD'),
    ('Air Indus', NULL, 'PP'),
    ('Air Italy', NULL, 'I9'),
    ('Air Ivoire', NULL, 'VU'),
    ('Air Jamaica', NULL, 'JM'),
    ('Air Japan', NULL, 'NQ'),
    ('Air Kazakhstan', NULL, '9Y'),
    ('Air Kenya (Priv)', NULL, 'QP'),
    ('Air Kiribati', NULL, '4A'),
    ('Air Koryo', NULL, 'JS'),
    ('Air Libert', NULL, 'VD'),
    ('Air Lituanica', NULL, 'LT'),
    ('Air Luxor', NULL, 'LK'),
    ('Air Macau', '에어마카오', 'NX'),
    ('Air Madagascar', NULL, 'MD'),
    ('Air Madrid', NULL, 'NM'),
    ('Air Malawi', NULL, 'QM'),
    ('Air Malta', NULL, 'KM'),
    ('Air Mandalay', NULL, '6T'),
    ('Air Marshall Islands', NULL, 'CW'),
    ('Air Mauritius', NULL, 'MK'),
    ('Air Mediterranee', NULL, 'DR'),
    ('Air Mekong', NULL, 'P8'),
    ('Air Moldova', NULL, '9U'),
    ('Air Mozambique', NULL, 'TM'),
    ('Air Namibia', NULL, 'SW'),
    ('Air New Zealand', '뉴질랜드항공', 'NZ'),
    ('Air Nippon', NULL, 'EL'),
    ('Air Niugini', NULL, 'PX'),
    ('Air North Charter - Canada', NULL, '4N'),
    ('Air Nostrum', NULL, 'YW'),
    ('Air One', NULL, 'AP'),
    ('Air Pacific', '피지항공', 'FJ'),
    ('Air Pegasus', NULL, 'OP'),
    ('Air Philippines', NULL, '2P'),
    ('Air Plus Comet', NULL, 'A7'),
    ('Air Premia', '에어프레미아', 'YP'),
    ('Air Rarotonga', NULL, 'GZ'),
    ('Air Sahara', NULL, 'S2'),
    ('Air Saint Pierre', NULL, 'PJ'),
    ('Air Salone', NULL, '2O'),
    ('Air Salone', NULL, '20'),
    ('Air Seoul', '에어서울', 'RS'),
    ('Air Serbia', NULL, 'JU'),
    ('Air Seychelles', NULL, 'HM'),
    ('Air Sicilia', NULL, 'BM'),
    ('Air Sinai', NULL, '4D'),
    ('Air Tahiti', NULL, 'VT'),
    ('Air Tahiti Nui', NULL, 'TN'),
    ('Air Tanzania', NULL, 'TC'),
    ('Air Tindi', NULL, '8T'),
    ('Air Transat', NULL, 'TS'),
    ('Air VIA', NULL, 'VL'),
    ('Air Vanuatu', NULL, 'NF'),
    ('Air Vistara', NULL, 'UK'),
    ('Air Volga', NULL, 'G6'),
    ('Air Wales', NULL, '6G'),
    ('Air Wisconsin', NULL, 'ZW'),
    ('Air Zimbabwe', NULL, 'UM'),
    ('Air2there', NULL, 'F8'),
    ('AirAsia', '에어아시아', 'AK'),
    ('AirAsia X', NULL, 'D7'),
    ('AirOnix', NULL, 'OG'),
    ('AirRussia', NULL, 'R8'),
    ('AirTran Airways', NULL, 'FL'),
    ('Airblue', NULL, 'ED'),
    ('Aircompany Yakutia', NULL, 'R3'),
    ('Aires', NULL, '4C'),
    ('Airlinair', NULL, 'A5'),
    ('Airlines Of Tasmania', NULL, 'FO'),
    ('Airlines PNG', NULL, 'CG'),
    ('Airlink (SAA)', NULL, '4Z'),
    ('Airnorth', NULL, 'TL'),
    ('Al-Naser Airlines', NULL, 'NA'),
    ('AlMasria Universal Airlines', NULL, 'UJ'),
    ('Alaska Airlines', '알래스카항공', 'AS'),
    ('Alaska Central Express', NULL, 'KO'),
    ('Alaska Seaplane Service', NULL, 'J5'),
    ('Albanian Airlines', NULL, 'LV'),
    ('Alitalia', '알리탈리아', 'AZ'),
    ('Alitalia Cityliner', NULL, 'CT'),
    ('Alitalia Express', NULL, 'XM'),
    ('All Africa', NULL, '9A'),
    ('All America', NULL, 'A2'),
    ('All America AR', NULL, '2R'),
    ('All America BOPY', NULL, '0P'),
    ('All America BR', NULL, '1Y'),
    ('All America CL', NULL, '1R'),
    ('All America CO', NULL, '0Y'),
    ('All America MX', NULL, '0M'),
    ('All America US', NULL, 'AG'),
    ('All Argentina', NULL, 'L1'),
    ('All Argentina Express', NULL, 'Z0'),
    ('All Asia', NULL, 'L9'),
    ('All Australia', NULL, '88'),
    ('All Colombia', NULL, '7O'),
    ('All Europe', NULL, 'N9'),
    ('All Nippon Airways', '전일본공수', 'NH'),
    ('All Spain', NULL, 'N7'),
    ('Allegiant Air', NULL, 'G4'),
    ('Alliance Airlines', NULL, 'QQ'),
    ('Aloha Airlines', NULL, 'AQ'),
    ('Alrosa Mirny Air Enterprise', NULL, '6R'),
    ('Amaszonas', NULL, 'Z8'),
    ('America West Airlines', NULL, 'HP'),
    ('American Airlines', '아메리칸항공', 'AA'),
    ('American Eagle Airlines', NULL, 'MQ'),
    ('Amsterdam Airlines', NULL, 'WD'),
    ('Ansett Australia', NULL, 'AN'),
    ('Apache Air', NULL, 'ZM'),
    ('Ariana Afghan Airlines', NULL, 'FG'),
    ('Arik Niger', NULL, 'Q9'),
    ('Arkefly', NULL, 'OR'),
    ('Arkia Israel Airlines', NULL, 'IZ'),
    ('Armavia', NULL, 'U8'),
    ('Arrow Air', NULL, 'JW'),
    ('Aserca Airlines', NULL, 'R7'),
    ('Asia Wings', NULL, 'Y5'),
    ('Asian Spirit', NULL, '6K'),
    ('Asian Wings Airways', NULL, 'AW'),
    ('Asiana Airlines', '아시아나항공', 'OZ'),
    ('Askari Aviation', NULL, '4K'),
    ('Astair', NULL, '8D'),
    ('Astraeus', NULL, '5W'),
    ('Astrakhan Airlines', NULL, 'OB'),
    ('Astral Aviation', NULL, '8V'),
    ('Athens Airways', NULL, 'ZF'),
    ('Atifly', NULL, 'A1'),
    ('Atlant-Soyuz Airlines', NULL, '3G'),
    ('Atlantic Airways', NULL, 'RC'),
    ('Atlantic Southeast Airlines', NULL, 'EV'),
    ('Atlantis European Airways', NULL, 'TD'),
    ('Atlas Air', NULL, '5Y'),
    ('Atlas Blue', NULL, '8A'),
    ('Atlasjet', NULL, 'KK'),
    ('Augsburg Airways', NULL, 'IQ'),
    ('Aurigny Air Services', NULL, 'GR'),
    ('Austral Brasil', NULL, 'W7'),
    ('Austral Lineas Aereas', NULL, 'AU'),
    ('Austrian Airlines', '오스트리아항공', 'OS'),
    ('Aviabus', NULL, 'U1'),
    ('Avialeasing Aviation Company', NULL, 'EC'),
    ('Avianca - Aerovias Nacionales de Colombia', '아비앙카', 'AV'),
    ('Avianova (Russia)', NULL, 'AO'),
    ('Avient Aviation', NULL, 'Z3'),
    ('Avies', NULL, 'U3'),
    ('Aws express', NULL, 'B0'),
    ('Azerbaijan Airlines', NULL, 'J2'),
    ('Azul', '아줄항공', 'AD'),
    ('BA CityFlyer', NULL, 'CJ'),
    ('BQB Lineas Aereas', NULL, '5Q'),
    ('BRAZIL AIR', NULL, 'GB'),
    ('BVI Airways', NULL, 'XV'),
    ('Bahamasair', NULL, 'UP'),
    ('Baikotovitchestrian Airlines', NULL, 'BU'),
    ('Balkan Bulgarian Airlines', NULL, 'LZ'),
    ('Baltic Air lines', NULL, 'B1'),
    ('Bangkok Airways', NULL, 'PG'),
    ('Barents AirLink', NULL, '8N'),
    ('Bassaka airlines', NULL, '5B'),
    ('Bearskin Lake Air Service', NULL, 'JV'),
    ('Belair Airlines', NULL, '4T'),
    ('Belavia Belarusian Airlines', NULL, 'B2'),
    ('Bellview Airlines', NULL, 'B3'),
    ('Bemidji Airlines', NULL, 'CH'),
    ('Bering Air', NULL, '8E'),
    ('Berjaya Air', NULL, 'J8'),
    ('Biman Bangladesh Airlines', NULL, 'BG'),
    ('Binter Canarias', NULL, 'NT'),
    ('Black Stallion Airways', NULL, 'BZ'),
    ('Blue Air', NULL, '0B'),
    ('Blue Panorama Airlines', NULL, 'BV'),
    ('Blue Wings', NULL, 'QW'),
    ('Blue1', NULL, 'KF'),
    ('Bobb Air Freight', NULL, '01'),
    ('Boutique Air (Priv)', NULL, '4B'),
    ('Brit Air', NULL, 'DB'),
    ('British Airways', '브리티시항공', 'BA'),
    ('British International Helicopters', NULL, 'BS'),
    ('British Mediterranean Airways', NULL, 'KJ'),
    ('Brussels Airlines', NULL, 'SN'),
    ('BudgetAir', NULL, '1K'),
    ('Bulgaria Air', NULL, 'FB'),
    ('Buquebus Líneas Aéreas', NULL, 'BQ'),
    ('Business Aviation', NULL, '4P'),
    ('BusinessAir', NULL, '8B'),
    ('CAL Cargo Air Lines', NULL, '5C'),
    ('CB Airways UK ( Interliging Flights )', NULL, '1F'),
    ('CCML Airlines', NULL, 'CB'),
    ('Calima Aviacion', NULL, 'XG'),
    ('Camair-co', NULL, 'QC'),
    ('Cambodia Angkor Air (K6)', NULL, 'K6'),
    ('CanXplorer', NULL, 'C2'),
    ('CanXpress', NULL, 'C1'),
    ('Canadian Airlines', NULL, 'CP'),
    ('Canadian National Airways', NULL, 'CN'),
    ('Canadian North', NULL, '5T'),
    ('Cape Air', NULL, '9K'),
    ('Cargo Plus Aviation', NULL, '8L'),
    ('Caribbean Airlines', NULL, 'BW'),
    ('Carnival Air Lines', NULL, 'KW'),
    ('Carpatair', NULL, 'V3'),
    ('Caspian Airlines', NULL, 'RV'),
    ('Cathay Pacific', '캐세이퍼시픽', 'CX'),
    ('Catovair', NULL, 'OC'),
    ('Caucasus Airlines', NULL, 'NS'),
    ('Cayman Airways', NULL, 'KX'),
    ('Cebu Pacific', '세부퍼시픽', '5J'),
    ('Centralwings', NULL, 'C0'),
    ('Chautauqua Airlines', NULL, 'RP'),
    ('China Airlines', '중화항공', 'CI'),
    ('China Eastern Airlines', '중국동방항공', 'MU'),
    ('China Northwest Airlines (WH)', NULL, 'WH'),
    ('China SSS', NULL, '9C'),
    ('China Southern Airlines', '중국남방항공', 'CZ'),
    ('China United', NULL, 'KN'),
    ('China United Airlines', NULL, 'HR'),
    ('Chongqing Airlines', NULL, 'OQ'),
    ('Ciao Air', NULL, '99'),
    ('Ciel Canadien', NULL, 'YC'),
    ('Cimber Air', NULL, 'QI'),
    ('Cirrus Airlines', NULL, 'C9'),
    ('Citilink Indonesia', NULL, 'QG'),
    ('City Airline', NULL, 'CF'),
    ('City Airways', NULL, 'E8'),
    ('CityJet', NULL, 'WX'),
    ('Click (Mexicana)', NULL, 'QA'),
    ('Coastal Air', NULL, 'DQ'),
    ('Colgan Air', NULL, '9L'),
    ('Comair', NULL, 'OH'),
    ('Comair', NULL, 'MN'),
    ('CommutAir', NULL, 'C5'),
    ('Comores Airlines', NULL, 'KR'),
    ('Compagnie Africaine d''Aviation', NULL, 'E9'),
    ('Condor Flugdienst', NULL, 'DE'),
    ('Congo Express', NULL, 'XZ'),
    ('Consorcio Aviaxsa', NULL, '6A'),
    ('Contact Air', NULL, 'C3'),
    ('Continental Airlines', NULL, 'CO'),
    ('Continental Micronesia', NULL, 'CS'),
    ('Conviasa', NULL, 'V0'),
    ('Copa Airlines', '코파항공', 'CM'),
    ('Copenhagen Express', NULL, '0X'),
    ('Corsairfly', NULL, 'SS'),
    ('Corse-Mediterranee', NULL, 'XK'),
    ('Croatia Airlines', NULL, 'OU'),
    ('Cubana de Aviación', NULL, 'CU'),
    ('Cyprus Airways', NULL, 'CY'),
    ('Cyprus Turkish Airlines', NULL, 'YK'),
    ('Czech Airlines', '체코항공', 'OK'),
    ('DAT Danish Air Transport', NULL, 'DX'),
    ('Daallo Airlines', NULL, 'D3'),
    ('Dalavia', NULL, 'H8'),
    ('Dana Air', NULL, 'DA'),
    ('Danube Wings (V5)', NULL, 'V5'),
    ('Darwin Airline', NULL, '0D'),
    ('Delta Air Lines', '델타항공', 'DL'),
    ('Denim Air', NULL, 'J7'),
    ('Dennis Sky', NULL, 'DH'),
    ('Dense Airways', NULL, 'KP'),
    ('Dense Connection', NULL, 'KZ'),
    ('Deutsche Bahn', NULL, '2A'),
    ('Djibouti Airlines', NULL, 'D8'),
    ('Dobrolet', NULL, 'QD'),
    ('Domenican Airlines', NULL, 'D1'),
    ('Dominicana de Aviaci', NULL, 'DO'),
    ('Domodedovo Airlines', NULL, 'E3'),
    ('Dragonair', NULL, 'KA'),
    ('Druk Air', NULL, 'KB'),
    ('EVA Air', '에바항공', 'BR'),
    ('Eagle Air', NULL, 'H7'),
    ('Eagle Atlantic Airlines', NULL, 'E2'),
    ('East African', NULL, 'QU'),
    ('Eastar Jet', '이스타항공', 'ZE'),
    ('Eastern Airways', NULL, 'T3'),
    ('Eastern Atlantic Virtual Airlines', NULL, '13'),
    ('Eastland Air', NULL, 'DK'),
    ('EasyJet (DS)', NULL, 'DS'),
    ('Edelweiss Air', NULL, 'WK'),
    ('Egyptair', '이집트항공', 'MS'),
    ('El Al Israel Airlines', '엘알이스라엘항공', 'LY'),
    ('El-Buraq Air Transport', NULL, 'UZ'),
    ('Elysian Airlines', NULL, 'E4'),
    ('Emirates', '에미레이트항공', 'EK'),
    ('Empresa Ecuatoriana De Aviacion', NULL, 'EU'),
    ('Epic Holiday', NULL, 'FA'),
    ('Era Alaska', NULL, '7H'),
    ('Eritrean Airlines', NULL, 'B8'),
    ('Estonian Air', NULL, 'OV'),
    ('Ethiopian Airlines', '에티오피아항공', 'ET'),
    ('Etihad Airways', '에티하드항공', 'EY'),
    ('Euro Exec Express', NULL, 'RZ'),
    ('Euro Jet', NULL, '24'),
    ('Eurocypria Airlines', NULL, 'UI'),
    ('Eurofly Service', NULL, 'GJ'),
    ('Euroline', NULL, '4L'),
    ('Eurolot', NULL, 'K2'),
    ('Europe Jet', NULL, 'EX'),
    ('EuropeSky', NULL, 'ES'),
    ('European Air Express', NULL, 'EA'),
    ('Eurowings', '유로윙스', 'EW'),
    ('Evergreen International Airlines', NULL, 'EZ'),
    ('Excel Airways', NULL, 'JN'),
    ('Express One International', NULL, 'EO'),
    ('ExpressJet', NULL, 'XE'),
    ('FOX Linhas Aereas', NULL, 'FX'),
    ('Far Eastern Air Transport', NULL, 'EF'),
    ('Felix Airways', NULL, 'FU'),
    ('Finnair', '핀에어', 'AY'),
    ('Finncomm Airlines', NULL, 'FC'),
    ('Firefly', NULL, 'FY'),
    ('First Air', NULL, '7F'),
    ('First Choice Airways', NULL, 'DP'),
    ('Flightline', NULL, 'B5'),
    ('Flightlink Tanzania', NULL, 'Z9'),
    ('Florida West International Airways', '에어로케이', 'RF'),
    ('Fly 6ix', NULL, '6I'),
    ('Fly Brasil', NULL, 'F1'),
    ('Fly Colombia ( Interliging Flights )', NULL, '3F'),
    ('Fly Dubai', NULL, 'FZ'),
    ('Fly Europa', NULL, 'ER'),
    ('Fly France', NULL, 'FF'),
    ('Fly One', NULL, 'F5'),
    ('Fly Romania', NULL, 'X5'),
    ('Fly540', NULL, '5H'),
    ('FlyHigh Airlines Ireland (FH)', NULL, 'FH'),
    ('FlyLal', NULL, 'TE'),
    ('FlyNordic', NULL, 'LF'),
    ('FlyPortugal', NULL, 'PO'),
    ('Flybaboo', NULL, 'F7'),
    ('Flybe', NULL, 'BE'),
    ('Flyglobespan', NULL, 'B4'),
    ('Freedom Air', NULL, 'FP'),
    ('Frontier Airlines', NULL, 'F9'),
    ('Frontier Flying Service', NULL, '2F'),
    ('Fuji Dream Airlines', NULL, 'JH'),
    ('GB Airways', NULL, 'GT'),
    ('GNB Linhas Aereas', NULL, 'GN'),
    ('Gabon Airlines', NULL, 'GY'),
    ('Gadair European Airlines', NULL, 'GP'),
    ('Garuda Indonesia', '가루다인도네시아', 'GA'),
    ('Gazpromavia', NULL, '4G'),
    ('Georgian Airways', NULL, 'A9'),
    ('Georgian National Airlines', NULL, 'QB'),
    ('German International Air Lines', NULL, 'GM'),
    ('GermanXL', NULL, 'GX'),
    ('Germania', NULL, 'ST'),
    ('Germanwings', NULL, '4U'),
    ('Ghana International Airlines', NULL, 'G0'),
    ('Global Airlines', NULL, '0G'),
    ('Globus', NULL, 'GH'),
    ('Go Air', NULL, 'G8'),
    ('GoJet Airlines', NULL, 'G7'),
    ('Gol Transportes Aéreos', '골항공', 'G3'),
    ('Golden Air', NULL, 'DC'),
    ('Gomelavia', NULL, 'YD'),
    ('Great Lakes Airlines', NULL, 'ZK'),
    ('Greenfly', NULL, 'XX'),
    ('Grupo TACA', NULL, 'TA'),
    ('Gryphon Airlines', NULL, '6P'),
    ('Gulf Air Bahrain', NULL, 'GF'),
    ('Hageland Aviation Services', NULL, 'H6'),
    ('Hainan Airlines', '하이난항공', 'HU'),
    ('Haiti Ambassador Airlines', NULL, '2T'),
    ('Halcyonair', NULL, '7Z'),
    ('Hamburg International', NULL, '4R'),
    ('Hankook Air US', NULL, 'H1'),
    ('Hankook Airline', NULL, 'HN'),
    ('Hapagfly', NULL, 'HF'),
    ('Harbour Air (Priv)', NULL, 'H3'),
    ('Hawaiian Airlines', '하와이안항공', 'HA'),
    ('Hawkair', NULL, 'BH'),
    ('Heli France', NULL, '8H'),
    ('Helijet', NULL, 'JB'),
    ('Hellas Jet', NULL, 'T4'),
    ('Hellenic Imperial Airways', NULL, 'HT'),
    ('Hello', NULL, 'HW'),
    ('Helvetic Airways', NULL, '2L'),
    ('Hex''Air', NULL, 'UD'),
    ('Hi Fly (5K)', NULL, '5K'),
    ('Himalayan Airlines', NULL, 'HC'),
    ('Hokkaido International Airlines', NULL, 'HD'),
    ('Homer Air', NULL, 'MR'),
    ('Hong Kong Airlines', NULL, 'HX'),
    ('Hong Kong Express Airways', '홍콩익스프레스', 'UO'),
    ('Horizon Air', NULL, 'QX'),
    ('Horizon Airlines', NULL, 'BN'),
    ('Huaxia', NULL, 'G5'),
    ('I-Fly', NULL, 'H5'),
    ('INAVIA Internacional', NULL, 'Z5'),
    ('Iberia Airlines', '이베리아항공', 'IB'),
    ('Iberia Express', NULL, 'I2'),
    ('Iberworld', NULL, 'TY'),
    ('Ibex Airlines', NULL, 'FW'),
    ('Icelandair', NULL, 'FI'),
    ('Imair Airlines', NULL, 'IK'),
    ('IndiGo Airlines', '인디고', '6E'),
    ('Indian Airlines', NULL, 'IC'),
    ('Indonesia AirAsia', NULL, 'QZ'),
    ('Indonesia Sky', NULL, 'I5'),
    ('Indonesian Airlines', NULL, 'IO'),
    ('Indya Airline Group', NULL, 'G1'),
    ('Insel Air (7I/INC) (Priv)', NULL, '7I'),
    ('Interair South Africa', NULL, 'D6'),
    ('Interjet (ABC Aerolineas)', NULL, '4O'),
    ('Interlink Airlines', NULL, 'ID'),
    ('International AirLink', NULL, 'I4'),
    ('International Europe', NULL, '9I'),
    ('Intersky', NULL, '3L'),
    ('Iran Air', NULL, 'IR'),
    ('Iran Aseman Airlines', NULL, 'EP'),
    ('Iraqi Airways', NULL, 'IA'),
    ('Island Air (WP)', NULL, 'WP'),
    ('Island Airlines', NULL, 'IS'),
    ('Island Express Air', NULL, '1X'),
    ('Island Spirit', NULL, 'IP'),
    ('Islas Airways', NULL, 'IF'),
    ('Islena De Inversiones', NULL, 'WC'),
    ('Israir', NULL, '6H'),
    ('Itek Air', NULL, 'GI'),
    ('IzAvia', NULL, 'I8'),
    ('JAL Express', NULL, 'JC'),
    ('JALways', NULL, 'JO'),
    ('Japan Air System', NULL, 'JD'),
    ('Japan Airlines', '일본항공', 'JL'),
    ('Japan Asia Airways', NULL, 'EG'),
    ('Japan Regio', NULL, 'ZX'),
    ('Japan Transocean Air', NULL, 'NU'),
    ('Jazeera Airways', NULL, 'J9'),
    ('Jeju Air', '제주항공', '7C'),
    ('Jet Airways', NULL, '9W'),
    ('Jet Airways', NULL, 'QJ'),
    ('Jet2.com', NULL, 'LS'),
    ('Jet4You', NULL, '8J'),
    ('JetBlue Airways', '젯블루', 'B6'),
    ('Jetairfly', NULL, 'JF'),
    ('Jetgo Australia', NULL, 'JG'),
    ('Jetstar Airways', '젯스타항공', 'JQ'),
    ('Jetstar Asia Airways', NULL, '3K'),
    ('Jetstar Japan', '젯스타재팬', 'GK'),
    ('Jetstar Pacific', NULL, 'BL'),
    ('Jettor Airlines', NULL, 'NR'),
    ('Jin Air', '진에어', 'LJ'),
    ('JobAir', NULL, '3B'),
    ('Joy Air', NULL, 'JR'),
    ('Juneyao Airlines', NULL, 'HO'),
    ('KD Avia', NULL, 'KD'),
    ('KLM Cityhopper', NULL, 'WA'),
    ('KLM Royal Dutch Airlines', 'KLM네덜란드항공', 'KL'),
    ('KSY', NULL, 'KY'),
    ('Kam Air', NULL, 'RQ'),
    ('Kavminvodyavia', NULL, 'KV'),
    ('Kenmore Air', NULL, 'M5'),
    ('Kenya Airways', '케냐항공', 'KQ'),
    ('Kharkiv Airlines', NULL, 'KH'),
    ('Kingfisher Airlines', NULL, 'IT'),
    ('Kish Air', NULL, 'Y9'),
    ('Kogalymavia Air Company', NULL, '7K'),
    ('KoralBlue Airlines', NULL, 'K7'),
    ('Korean Air', '대한항공', 'KE'),
    ('Korongo Airlines', NULL, 'ZC'),
    ('Kostromskie avialinii', NULL, 'K1'),
    ('Krasnojarsky Airlines', NULL, '7B'),
    ('Kuban Airlines', NULL, 'GW'),
    ('Kuwait Airways', NULL, 'KU'),
    ('Kuzu Airlines Cargo', NULL, 'GO'),
    ('L', NULL, 'MJ'),
    ('LACSA', NULL, 'LR'),
    ('LAN Airlines', '라탐항공', 'LA'),
    ('LAN Argentina', NULL, '4M'),
    ('LAN Express', NULL, 'LU'),
    ('LAN Peru', NULL, 'LP'),
    ('LCM AIRLINES', NULL, 'LQ'),
    ('LOT Polish Airlines', 'LOT폴란드항공', 'LO'),
    ('LSM AIRLINES', NULL, 'YZ'),
    ('LSM Airlines', NULL, 'PQ'),
    ('LSM International', NULL, 'II'),
    ('LTE International Airways', NULL, 'XO'),
    ('LTU Austria', NULL, 'L3'),
    ('Lao Airlines', NULL, 'QV'),
    ('Lauda Air', NULL, 'NG'),
    ('Leeward Islands Air Transport', NULL, 'LI'),
    ('Liberty Airways', NULL, 'LE'),
    ('Libyan Arab Airlines', NULL, 'LN'),
    ('Line Blue', NULL, 'L8'),
    ('Linhas A', NULL, 'LM'),
    ('Lion Mentari Airlines', '라이온에어', 'JT'),
    ('LionXpress', NULL, 'C4'),
    ('Locair', NULL, 'ZQ'),
    ('Luchsh Airlines', NULL, 'L4'),
    ('Luftfahrtgesellschaft Walter', NULL, 'HE'),
    ('Lufthansa', '루프트한자', 'LH'),
    ('Lufthansa CityLine', NULL, 'CL'),
    ('Lufttransport', NULL, 'L5'),
    ('Lugansk Airlines', NULL, 'L7'),
    ('Luxair', NULL, 'LG'),
    ('MAT Airways', NULL, '6F'),
    ('MAT Macedonian Airlines', NULL, 'IN'),
    ('MDLR Airlines', NULL, '9H'),
    ('MHS Aviation GmbH', NULL, 'M2'),
    ('MIAT Mongolian Airlines', NULL, 'OM'),
    ('MNG Airlines', NULL, 'MB'),
    ('Maastricht Airlines', NULL, 'W2'),
    ('Maersk', NULL, 'DM'),
    ('Mahan Air', NULL, 'W5'),
    ('Malawian Airlines', NULL, '3W'),
    ('Malaysia Airlines', '말레이시아항공', 'MH'),
    ('Maldivian', NULL, 'Q2'),
    ('Maldivo Airlines', NULL, 'ML'),
    ('Malindo Air', NULL, 'OD'),
    ('Malmö Aviation', NULL, 'TF'),
    ('Malta Air Charter', NULL, 'R5'),
    ('Malév', NULL, 'MA'),
    ('Mandala Airlines', NULL, 'RI'),
    ('Mandarin Airlines', NULL, 'AE'),
    ('Mango', NULL, 'JE'),
    ('Martinair', NULL, 'MP'),
    ('Marusya Airways', NULL, 'Y8'),
    ('Maryland Air', NULL, 'M1'),
    ('Marysya Airlines', NULL, 'M4'),
    ('MasAir', NULL, 'M7'),
    ('Mauritania Airlines International', NULL, 'L6'),
    ('Maxair', NULL, '8M'),
    ('Maya Island Air', NULL, 'MW'),
    ('Med Airways', NULL, '7Y'),
    ('Meridiana', NULL, 'IG'),
    ('Merpati Nusantara Airlines', NULL, 'MZ'),
    ('Mesa Airlines', NULL, 'YV'),
    ('Mesaba Airlines', NULL, 'XJ'),
    ('Metro Batavia', NULL, '7P'),
    ('Mexicana de Aviaci', NULL, 'MX'),
    ('MexicanaLink', NULL, 'I6'),
    ('Michael Airlines', NULL, 'DF'),
    ('Middle East Airlines', NULL, 'ME'),
    ('Midway Airlines', NULL, 'JI'),
    ('Midwest Airlines', NULL, 'YX'),
    ('Midwest Airlines (Egypt)', NULL, 'MY'),
    ('Moldavian Airlines', NULL, '2M'),
    ('Mongolian International Air Lines', NULL, '7M'),
    ('Montenegro Airlines', NULL, 'YM'),
    ('Moskovia Airlines', NULL, '3R'),
    ('Motor Sich', NULL, 'M9'),
    ('MyTravel Airways', NULL, 'VZ'),
    ('Myanma Airways', NULL, 'UB'),
    ('Myway Airlines', NULL, '8I'),
    ('N1', NULL, 'N1'),
    ('NEXT Brasil', NULL, 'XB'),
    ('Nas Air', NULL, 'XY'),
    ('Nasair', NULL, 'UE'),
    ('National Air Cargo', NULL, 'N8'),
    ('National Jet Systems', NULL, 'NC'),
    ('Nationwide Airlines', NULL, 'CE'),
    ('Nauru Air Corporation', NULL, 'ON'),
    ('Nepal Airlines', NULL, 'RA'),
    ('NetJets', NULL, '1I'),
    ('New England Airlines', NULL, 'EJ'),
    ('NextJet', NULL, '2N'),
    ('Niki', NULL, 'HG'),
    ('Nile Air', NULL, 'NP'),
    ('Nok Air', NULL, 'DD'),
    ('NordStar Airlines', NULL, 'Y7'),
    ('Nordic Global Airlines', NULL, 'NJ'),
    ('Nordica', NULL, 'EE'),
    ('Norte Lineas Aereas', NULL, 'N0'),
    ('Northern Dene Airways', NULL, 'U7'),
    ('Northwest Airlines', NULL, 'NW'),
    ('Northwestern Air', NULL, 'J3'),
    ('Norwegian Air Shuttle', '노르웨이지안항공', 'DY'),
    ('Norwegian Long Haul AS', NULL, 'DU'),
    ('Nouvel Air Tunisie', NULL, 'BJ'),
    ('Oasis Hong Kong Airlines', NULL, 'O8'),
    ('Oceanair', NULL, 'O6'),
    ('Oceanic Airlines', NULL, 'O2'),
    ('Olympic Airlines', NULL, 'OA'),
    ('Oman Air', NULL, 'WY'),
    ('Omni Air International', NULL, 'OY'),
    ('OneChina', NULL, '1C'),
    ('OneJet', NULL, 'J1'),
    ('Onur Air', NULL, '8Q'),
    ('Orbit Airlines Azerbaijan', NULL, 'O1'),
    ('Orchid Airlines', NULL, 'OI'),
    ('Orenburg Airlines', NULL, 'R2'),
    ('Orient Thai Airlines', NULL, 'OX'),
    ('Origin Pacific Airways', NULL, 'QO'),
    ('Ostfriesische Lufttransport', NULL, 'OL'),
    ('Overland Airways', NULL, 'OJ'),
    ('Ozjet Airlines', NULL, 'O7'),
    ('PAN Air', NULL, 'PV'),
    ('PB Air', NULL, '9Q'),
    ('PEGASUS AIRLINES-', NULL, 'H9'),
    ('PLUNA', NULL, 'PU'),
    ('PMTair', NULL, 'U4'),
    ('Pacific Coastal Airline', NULL, '8P'),
    ('Pacific East Asia Cargo Airlines', NULL, 'Q8'),
    ('Pacific Wings', NULL, 'LW'),
    ('Pakistan International Airlines', NULL, 'PK'),
    ('Pal airlines', NULL, '5P'),
    ('Pan Am World Airways Dominicana', NULL, '7Q'),
    ('PanAm World Airways', NULL, 'WQ'),
    ('Papillon Grand Canyon Helicopters', NULL, 'HI'),
    ('Paramount Airways', NULL, 'I7'),
    ('Parmiss Airlines (IPV)', NULL, 'PA'),
    ('Patriot Airways', NULL, 'P4'),
    ('Peach Aviation', '피치항공', 'MM'),
    ('Pegasus Airlines', NULL, 'PC'),
    ('Pelita', NULL, '6D'),
    ('Peninsula Airways', NULL, 'KS'),
    ('Peruvian Airlines', NULL, 'P9'),
    ('Philippine Airlines', '필리핀항공', 'PR'),
    ('Piedmont Airlines (1948-1989)', NULL, 'PI'),
    ('Pinnacle Airlines', NULL, '9E'),
    ('Polet Airlines (Priv)', NULL, 'YQ'),
    ('Polynesian Airlines', NULL, 'PH'),
    ('Porter Airlines', NULL, 'PD'),
    ('Portugalia', NULL, 'NI'),
    ('Potomac Air', NULL, 'BK'),
    ('Precision Air', NULL, 'PW'),
    ('Primera Air', NULL, 'PF'),
    ('Proflight Commuter Services', NULL, 'P0'),
    ('Qantas', '콴타스항공', 'QF'),
    ('Qatar Airways', '카타르항공', 'QR'),
    ('RACSA', NULL, 'R6'),
    ('REDjet', NULL, 'Z7'),
    ('REXAIR VIRTUEL', NULL, 'RR'),
    ('Rainbow Air (RAI)', NULL, 'RN'),
    ('Rainbow Air Canada', NULL, 'RY'),
    ('Rainbow Air Euro', NULL, 'RU'),
    ('Rainbow Air Polynesia', NULL, 'RX'),
    ('Rainbow Air US', NULL, 'RM'),
    ('Real Tonga', NULL, 'RT'),
    ('Red Jet Andes', NULL, 'PT'),
    ('Red Jet Canada', NULL, 'QY'),
    ('Red Jet Mexico', NULL, '4X'),
    ('Red Wings', NULL, 'WZ'),
    ('Regional Air Iceland', NULL, '9N'),
    ('Regional Airlines', NULL, 'FN'),
    ('Regional Express', NULL, 'ZL'),
    ('Regional Paraguaya', NULL, 'P7'),
    ('Regionalia Chile', NULL, '9J'),
    ('Regionalia México', NULL, 'N4'),
    ('Regionalia Uruguay', NULL, '2X'),
    ('Regionalia Venezuela', NULL, '9X'),
    ('Republic Airlines', NULL, 'RW'),
    ('Republic Express Airlines', NULL, 'RH'),
    ('Rossiya', NULL, 'R4'),
    ('Rossiya-Russian Airlines', NULL, 'FV'),
    ('Royal Air Maroc', '모로코항공', 'AT'),
    ('Royal Airways', NULL, 'KG'),
    ('Royal Brunei Airlines', NULL, 'BI'),
    ('Royal European Airlines', NULL, '69'),
    ('Royal Falcon', NULL, 'RL'),
    ('Royal Jordanian', NULL, 'RJ'),
    ('Rwandair Express', NULL, 'WB'),
    ('Ryan International Airlines', NULL, 'RD'),
    ('Ryanair', '라이언에어', 'FR'),
    ('Régional', NULL, 'YS'),
    ('S7 Airlines', NULL, 'S7'),
    ('SATA Air Acores', NULL, 'SP'),
    ('SATA International', NULL, 'S4'),
    ('SATENA', NULL, '9R'),
    ('SENIC AIRLINES', NULL, 'YR'),
    ('SGA Airlines', NULL, '5E'),
    ('SOCHI AIR', NULL, 'CQ'),
    ('SOCHI AIR CHATER', NULL, 'Q3'),
    ('SOCHI AIR EXPRESS', NULL, 'Q4'),
    ('STARLUX Airlines', '스타럭스항공', 'JX'),
    ('STP Airways', NULL, '8F'),
    ('Safi Airlines', NULL, '4Q'),
    ('Salmon Air', NULL, 'S6'),
    ('Salsa d''Haiti', NULL, 'SO'),
    ('Salzburg arrows', NULL, 'SZ'),
    ('Sama Airlines', NULL, 'ZS'),
    ('Santa Barbara Airlines', NULL, 'S3'),
    ('Saratov Aviation Division', NULL, '6W'),
    ('Sat Airlines', NULL, 'HZ'),
    ('Saudi Arabian Airlines', '사우디아항공', 'SV'),
    ('Scandinavian Airlines System', '스칸디나비아항공', 'SK'),
    ('Scat Air', NULL, 'DV'),
    ('Scoot', NULL, 'TZ'),
    ('SeaPort Airlines', NULL, 'K5'),
    ('Seaborne Airlines', NULL, 'BB'),
    ('Senegal Airlines', NULL, 'DN'),
    ('Serbian Airlines', NULL, 'S1'),
    ('Servicios de Transportes A', NULL, 'FS'),
    ('Severstal Air Company', NULL, 'D2'),
    ('Shaheen Air International', NULL, 'NL'),
    ('Shandong Airlines', NULL, 'SC'),
    ('Shanghai Airlines', NULL, 'FM'),
    ('Sharp Airlines', NULL, 'SH'),
    ('Shenzhen Airlines', NULL, 'ZH'),
    ('Shuttle America', NULL, 'S5'),
    ('Sibaviatrans', NULL, '5M'),
    ('Sichuan Airlines', '쓰촨항공', '3U'),
    ('Siem Reap Airways', NULL, 'FT'),
    ('SilkAir', NULL, 'MI'),
    ('Silver Airways (3M)', NULL, '3M'),
    ('Singapore Airlines', '싱가포르항공', 'SQ'),
    ('Skagway Air Service', NULL, 'N5'),
    ('Sky Airline', NULL, 'H2'),
    ('Sky Express', NULL, 'XW'),
    ('Sky Wing Pacific', NULL, 'C7'),
    ('SkyBahamas Airlines', NULL, 'Q7'),
    ('SkyEurope', NULL, 'NE'),
    ('SkyWest', NULL, 'OO'),
    ('SkyWork Airlines', NULL, 'SX'),
    ('Skyjet Airlines', NULL, 'UQ'),
    ('Skymark Airlines', '스카이마크', 'BC'),
    ('Skynet Airlines', NULL, 'SI'),
    ('Skynet Asia Airways', NULL, '6J'),
    ('Skyservice Airlines', NULL, '5G'),
    ('Skywalk Airlines', NULL, 'AL'),
    ('Skyways Express', NULL, 'JZ'),
    ('Skywest Australia', NULL, 'XR'),
    ('SmartLynx Airlines', NULL, '6Y'),
    ('Snowbird Airlines', NULL, 'S8'),
    ('Solomon Airlines', NULL, 'IE'),
    ('South African Airways', '남아프리카항공', 'SA'),
    ('South East Asian Airlines', NULL, 'DG'),
    ('Southern Winds Airlines', NULL, 'A4'),
    ('Southjet', NULL, '76'),
    ('Southjet cargo', NULL, '78'),
    ('Southjet connect', NULL, '77'),
    ('Southwest Airlines', '사우스웨스트항공', 'WN'),
    ('Spanair', NULL, 'JK'),
    ('Spicejet', NULL, 'SG'),
    ('Spike Airlines', NULL, 'S0'),
    ('Spirit Airlines', NULL, 'NK'),
    ('Spirit of Manila Airlines', NULL, 'SM'),
    ('Spring Airlines', NULL, '9S'),
    ('Spring Airlines Japan', NULL, 'IJ'),
    ('SriLankan Airlines', '스리랑칸항공', 'UL'),
    ('Sriwijaya Air', NULL, 'SJ'),
    ('Star Flyer', NULL, '7G'),
    ('Star Peru (2I)', NULL, '2I'),
    ('Star1 Airlines', NULL, 'V9'),
    ('Starbow Airlines', NULL, 'S9'),
    ('Starline.kz', NULL, 'DZ'),
    ('Sterling Airlines', NULL, 'NB'),
    ('Strategic Airlines', NULL, 'VC'),
    ('Sudan Airways', NULL, 'SD'),
    ('Sun Country Airlines', NULL, 'SY'),
    ('Sun D''Or', NULL, '7L'),
    ('SunExpress', NULL, 'XQ'),
    ('Sunwing', NULL, 'WG'),
    ('Surinam Airways', NULL, 'PY'),
    ('Svyaz Rossiya', NULL, '7R'),
    ('Swe Fly', NULL, 'WV'),
    ('Swiss International Air Lines', '스위스국제항공', 'LX'),
    ('Swissair', NULL, 'SR'),
    ('Syrian Arab Airlines', NULL, 'RB'),
    ('T.J. Air', NULL, 'TJ'),
    ('TAAG Angola Airlines', NULL, 'DT'),
    ('TACA Peru', NULL, 'T0'),
    ('TACV', NULL, 'VR'),
    ('TAM Brazilian Airlines', NULL, 'JJ'),
    ('TAM Mercosur', NULL, 'PZ'),
    ('TAME', NULL, 'EQ'),
    ('TAMPA', NULL, 'QT'),
    ('TAP Portugal', 'TAP포르투갈항공', 'TP'),
    ('TRIP Linhas A', NULL, '8R'),
    ('TUIfly', NULL, 'X3'),
    ('TUIfly (X3)', NULL, '11'),
    ('TUIfly Nordic', NULL, '6B'),
    ('Tajik Air', NULL, '7J'),
    ('Tarom', NULL, 'RO'),
    ('Tatarstan Airlines', NULL, 'U9'),
    ('Texas Wings', NULL, 'TQ'),
    ('Thai Air Cargo', NULL, 'T2'),
    ('Thai AirAsia', '타이에어아시아', 'FD'),
    ('Thai Airways International', '타이항공', 'TG'),
    ('Thai Lion Air', NULL, 'SL'),
    ('Thai Smile Airways', NULL, 'WE'),
    ('Thomas Cook Airlines', NULL, 'FQ'),
    ('Thomas Cook Airlines', NULL, 'MT'),
    ('Thomsonfly', NULL, 'BY'),
    ('Tiara Air', NULL, '3P'),
    ('Tiger Airways', '스쿠트', 'TR'),
    ('Tiger Airways Australia', NULL, 'TT'),
    ('Tomp Airlines', NULL, 'ZT'),
    ('Trans Pas Air', NULL, 'T6'),
    ('Trans States Airlines', NULL, 'AX'),
    ('TransAsia Airways', NULL, 'GE'),
    ('TransBrasil Airlines', NULL, 'TH'),
    ('TransHolding', NULL, 'TI'),
    ('TransHolding System', NULL, 'YO'),
    ('TransNusa Air', NULL, 'M8'),
    ('TransRussiaAirlines', NULL, '1E'),
    ('Transaero Airlines', NULL, 'UN'),
    ('Transavia France', NULL, 'TO'),
    ('Transavia Holland', NULL, 'HV'),
    ('Transwest Air', NULL, '9T'),
    ('TrasBrasil', NULL, 'TB'),
    ('Travel Service', NULL, 'QS'),
    ('Tropic Air', NULL, 'PM'),
    ('Tuninter', NULL, 'UG'),
    ('Tunisair', NULL, 'TU'),
    ('Turan Air', NULL, '3T'),
    ('Turkish Airlines', '터키항공', 'TK'),
    ('Turkmenistan Airlines', NULL, 'T5'),
    ('Tway Airlines', '티웨이항공', 'TW'),
    ('Twin Jet', NULL, 'T7'),
    ('Tyrolean Airways', NULL, 'VO'),
    ('UM Airlines', NULL, 'UF'),
    ('US Airways', NULL, 'US'),
    ('US Helicopter Corporation', NULL, 'UH'),
    ('USA3000 Airlines', NULL, 'U5'),
    ('UTair Aviation', NULL, 'UT'),
    ('UTair-Express', NULL, 'UR'),
    ('UVT Aero', NULL, 'UW'),
    ('Ukraine International Airlines', NULL, 'PS'),
    ('Uni Air', NULL, 'B7'),
    ('United Airlines', '유나이티드항공', 'UA'),
    ('United Airways', NULL, '4H'),
    ('Ural Airlines', NULL, 'U6'),
    ('Usa Sky Cargo', NULL, 'E1'),
    ('Uzbekistan Airways', NULL, 'HY'),
    ('V Air', NULL, 'ZV'),
    ('VASP', NULL, 'VP'),
    ('VIA Líneas Aéreas', NULL, 'V1'),
    ('VIM Airlines', NULL, 'NN'),
    ('VIP Ecuador', NULL, 'V6'),
    ('VLM Airlines', NULL, 'VG'),
    ('VOLOTEA Airways', NULL, 'V7'),
    ('VRG Linhas Aereas', NULL, 'RG'),
    ('Valuair', NULL, 'VF'),
    ('Varig Log', NULL, 'LC'),
    ('Via Conectia Airlines', NULL, '6V'),
    ('VickJet', NULL, 'KT'),
    ('VietJet Aviation', '비엣젯항공', 'VJ'),
    ('Vietnam Airlines', '베트남항공', 'VN'),
    ('Viking Hellas', NULL, 'VQ'),
    ('Virgin America', NULL, 'VX'),
    ('Virgin Atlantic Airways', '버진애틀랜틱', 'VS'),
    ('Virgin Australia', '버진오스트레일리아', 'VA'),
    ('Virgin Express', NULL, 'TV'),
    ('Virgin Nigeria Airways', NULL, 'VK'),
    ('Virgin Pacific', NULL, 'VH'),
    ('Virginwings', NULL, 'YY'),
    ('Vision Airlines (V2)', NULL, 'V2'),
    ('Viva Macau', NULL, 'ZG'),
    ('VivaColombia', NULL, '5Z'),
    ('Vladivostok Air', NULL, 'XF'),
    ('Voestar', NULL, '8K'),
    ('Volare Airlines', NULL, 'VE'),
    ('Volaris', NULL, 'Y4'),
    ('Volga-Dnepr Airlines', NULL, 'VI'),
    ('Volotea Costa Rica', NULL, '9V'),
    ('Vuela Cuba', NULL, '6C'),
    ('Vueling Airlines', NULL, 'VY'),
    ('Vuola Italia', NULL, '4S'),
    ('Wayraper', NULL, '7W'),
    ('WebJet Linhas A', NULL, 'WJ'),
    ('Welcome Air', NULL, '2W'),
    ('West Air China', NULL, 'PN'),
    ('West Coast Air', NULL, '8O'),
    ('WestJet', '웨스트젯', 'WS'),
    ('WestJet Encore', NULL, 'WR'),
    ('Widerøe', NULL, 'WF'),
    ('Wind Jet', NULL, 'IV'),
    ('Windward Islands Airways', NULL, 'WM'),
    ('Wings Air', NULL, 'IW'),
    ('Wizz Air', '위즈에어', 'W6'),
    ('Wizz Air Hungary', NULL, '8Z'),
    ('Wizz Air Ukraine', NULL, 'WU'),
    ('World Airways', NULL, 'WO'),
    ('World Experience Airline', NULL, 'W1'),
    ('World Scale Airlines', NULL, 'W3'),
    ('XAIR USA', NULL, 'XA'),
    ('XL Airways France', NULL, 'SE'),
    ('XPTO', NULL, 'XP'),
    ('Xiamen Airlines', '샤먼항공', 'MF'),
    ('Xpressair', NULL, 'XN'),
    ('Yamal Airlines', NULL, 'YL'),
    ('Yangon Airways', NULL, 'HK'),
    ('Yangon Airways Ltd.', NULL, 'YH'),
    ('Yellowstone Club Private Shuttle', NULL, 'Y1'),
    ('Yellowtail', NULL, 'YE'),
    ('Yemenia', NULL, 'IY'),
    ('Yeti Airways', NULL, 'YT'),
    ('Yunnan Airlines', NULL, '3Q'),
    ('ZABAIKAL AIRLINES', NULL, 'Z6'),
    ('Zabaykalskii Airlines', NULL, 'ZP'),
    ('Zambezi Airlines (ZMA)', NULL, 'ZJ'),
    ('Zambia Skyways', NULL, 'K8'),
    ('Zenith International Airline', NULL, 'ZN'),
    ('Zest Air', NULL, 'Z2'),
    ('Zoom Airlines', NULL, 'Z4'),
    ('Zz', NULL, 'ZZ'),
    ('bmi', NULL, 'BD'),
    ('bmibaby', NULL, 'WW'),
    ('dba', NULL, 'DI'),
    ('easyJet', '이지젯', 'U2');
