INSERT INTO tag (name, tag_type) VALUES
-- ACTIVITY
('여행', 'ACTIVITY'),
('맛집 탐방', 'ACTIVITY'),
('카페 탐방', 'ACTIVITY'),
('쇼핑', 'ACTIVITY'),
('문화생활', 'ACTIVITY'),
('사진 촬영', 'ACTIVITY'),
('공부', 'ACTIVITY'),
('파티', 'ACTIVITY'),
('언어교환', 'ACTIVITY'),
('생활 도움', 'ACTIVITY'),
('투어', 'ACTIVITY'),
('운동', 'ACTIVITY'),
-- INTEREST
('자연', 'INTEREST'),
('도시', 'INTEREST'),
('예술', 'INTEREST'),
('게임', 'INTEREST'),
('영화', 'INTEREST'),
('음악', 'INTEREST'),
('운동', 'INTEREST'),
('요리', 'INTEREST'),
('역사', 'INTEREST'),
('패션', 'INTEREST'),
('사진', 'INTEREST'),
('독서', 'INTEREST'),
('휴양', 'INTEREST'),
('액티비티', 'INTEREST'),
-- TRAVEL_STYLE
('계획형', 'TRAVEL_STYLE'),
('즉흥형', 'TRAVEL_STYLE'),
('조용한', 'TRAVEL_STYLE'),
('활발한', 'TRAVEL_STYLE'),
('각자 시간 존중', 'TRAVEL_STYLE'),
('아침형', 'TRAVEL_STYLE'),
('여유롭게', 'TRAVEL_STYLE'),
('함께 다니기', 'TRAVEL_STYLE'),
('저녁형', 'TRAVEL_STYLE'),
('알차게', 'TRAVEL_STYLE');