UPDATE magazine
SET category = CASE
    WHEN LOWER(CONCAT(title, ' ', summary)) LIKE '%여행%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%관광%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%맛집%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%명소%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%여행지%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%여행 코스%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%숙소%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%주말여행%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%투어%'
        THEN 'TRAVEL'
    WHEN LOWER(CONCAT(title, ' ', summary)) LIKE '%출국%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%비자%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%여권%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%항공%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%비행기%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%짐%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%준비물%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%보험%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%출국 준비%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%환전%'
        THEN 'DEPARTURE_PREP'
    WHEN LOWER(CONCAT(title, ' ', summary)) LIKE '%기숙사%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%집 구하기%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%자취%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%은행%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%계좌%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%유심%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%esim%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%통신%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%교통%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%장보기%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%마트%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%현지 생활%'
        OR LOWER(CONCAT(title, ' ', summary)) LIKE '%정착%'
        THEN 'LOCAL_SETTLEMENT'
    ELSE 'SUPPORT'
END
WHERE category IS NULL;

ALTER TABLE magazine
    MODIFY COLUMN category VARCHAR(30) NOT NULL;
