ALTER TABLE country
    ADD COLUMN english_name VARCHAR(100) NULL;

UPDATE country
SET english_name = CASE iso_code
    WHEN 'GH' THEN 'Ghana'
    WHEN 'GA' THEN 'Gabon'
    WHEN 'GY' THEN 'Guyana'
    WHEN 'GM' THEN 'Gambia'
    WHEN 'GG' THEN 'Guernsey'
    WHEN 'GP' THEN 'Guadeloupe'
    WHEN 'GT' THEN 'Guatemala'
    WHEN 'GU' THEN 'Guam'
    WHEN 'GD' THEN 'Grenada'
    WHEN 'GR' THEN 'Greece'
    WHEN 'GL' THEN 'Greenland'
    WHEN 'GN' THEN 'Guinea'
    WHEN 'GW' THEN 'Guinea-Bissau'
    WHEN 'NA' THEN 'Namibia'
    WHEN 'NR' THEN 'Nauru'
    WHEN 'NG' THEN 'Nigeria'
    WHEN 'AQ' THEN 'Antarctica'
    WHEN 'SS' THEN 'South Sudan'
    WHEN 'ZA' THEN 'South Africa'
    WHEN 'NL' THEN 'Netherlands'
    WHEN 'BQ' THEN 'Caribbean Netherlands'
    WHEN 'NP' THEN 'Nepal'
    WHEN 'NO' THEN 'Norway'
    WHEN 'NF' THEN 'Norfolk Island'
    WHEN 'NZ' THEN 'New Zealand'
    WHEN 'NC' THEN 'New Caledonia'
    WHEN 'NU' THEN 'Niue'
    WHEN 'NE' THEN 'Niger'
    WHEN 'NI' THEN 'Nicaragua'
    WHEN 'TW' THEN 'Taiwan'
    WHEN 'KR' THEN 'South Korea'
    WHEN 'DK' THEN 'Denmark'
    WHEN 'DO' THEN 'Dominican Republic'
    WHEN 'DM' THEN 'Dominica'
    WHEN 'DE' THEN 'Germany'
    WHEN 'TL' THEN 'Timor-Leste'
    WHEN 'LA' THEN 'Laos'
    WHEN 'LR' THEN 'Liberia'
    WHEN 'LV' THEN 'Latvia'
    WHEN 'RU' THEN 'Russia'
    WHEN 'LB' THEN 'Lebanon'
    WHEN 'LS' THEN 'Lesotho'
    WHEN 'RE' THEN 'Réunion'
    WHEN 'RO' THEN 'Romania'
    WHEN 'LU' THEN 'Luxembourg'
    WHEN 'RW' THEN 'Rwanda'
    WHEN 'LY' THEN 'Libya'
    WHEN 'LT' THEN 'Lithuania'
    WHEN 'LI' THEN 'Liechtenstein'
    WHEN 'MG' THEN 'Madagascar'
    WHEN 'MQ' THEN 'Martinique'
    WHEN 'MH' THEN 'Marshall Islands'
    WHEN 'YT' THEN 'Mayotte'
    WHEN 'MO' THEN 'Macao SAR China'
    WHEN 'MW' THEN 'Malawi'
    WHEN 'MY' THEN 'Malaysia'
    WHEN 'ML' THEN 'Mali'
    WHEN 'IM' THEN 'Isle of Man'
    WHEN 'MX' THEN 'Mexico'
    WHEN 'MC' THEN 'Monaco'
    WHEN 'MA' THEN 'Morocco'
    WHEN 'MU' THEN 'Mauritius'
    WHEN 'MR' THEN 'Mauritania'
    WHEN 'MZ' THEN 'Mozambique'
    WHEN 'ME' THEN 'Montenegro'
    WHEN 'MS' THEN 'Montserrat'
    WHEN 'MD' THEN 'Moldova'
    WHEN 'MV' THEN 'Maldives'
    WHEN 'MT' THEN 'Malta'
    WHEN 'MN' THEN 'Mongolia'
    WHEN 'US' THEN 'United States'
    WHEN 'VI' THEN 'U.S. Virgin Islands'
    WHEN 'UM' THEN 'U.S. Outlying Islands'
    WHEN 'MM' THEN 'Myanmar (Burma)'
    WHEN 'FM' THEN 'Micronesia'
    WHEN 'VU' THEN 'Vanuatu'
    WHEN 'BH' THEN 'Bahrain'
    WHEN 'BB' THEN 'Barbados'
    WHEN 'VA' THEN 'Vatican City'
    WHEN 'BS' THEN 'Bahamas'
    WHEN 'BD' THEN 'Bangladesh'
    WHEN 'BM' THEN 'Bermuda'
    WHEN 'BJ' THEN 'Benin'
    WHEN 'VE' THEN 'Venezuela'
    WHEN 'VN' THEN 'Vietnam'
    WHEN 'BE' THEN 'Belgium'
    WHEN 'BY' THEN 'Belarus'
    WHEN 'BZ' THEN 'Belize'
    WHEN 'BA' THEN 'Bosnia & Herzegovina'
    WHEN 'BW' THEN 'Botswana'
    WHEN 'BO' THEN 'Bolivia'
    WHEN 'BI' THEN 'Burundi'
    WHEN 'BF' THEN 'Burkina Faso'
    WHEN 'BV' THEN 'Bouvet Island'
    WHEN 'BT' THEN 'Bhutan'
    WHEN 'MP' THEN 'Northern Mariana Islands'
    WHEN 'MK' THEN 'North Macedonia'
    WHEN 'KP' THEN 'North Korea'
    WHEN 'BG' THEN 'Bulgaria'
    WHEN 'BR' THEN 'Brazil'
    WHEN 'BN' THEN 'Brunei'
    WHEN 'WS' THEN 'Samoa'
    WHEN 'SA' THEN 'Saudi Arabia'
    WHEN 'GS' THEN 'South Georgia & South Sandwich Islands'
    WHEN 'SM' THEN 'San Marino'
    WHEN 'ST' THEN 'São Tomé & Príncipe'
    WHEN 'MF' THEN 'St. Martin'
    WHEN 'BL' THEN 'St. Barthélemy'
    WHEN 'PM' THEN 'St. Pierre & Miquelon'
    WHEN 'EH' THEN 'Western Sahara'
    WHEN 'SN' THEN 'Senegal'
    WHEN 'RS' THEN 'Serbia'
    WHEN 'SC' THEN 'Seychelles'
    WHEN 'LC' THEN 'St. Lucia'
    WHEN 'VC' THEN 'St. Vincent & Grenadines'
    WHEN 'KN' THEN 'St. Kitts & Nevis'
    WHEN 'SH' THEN 'St. Helena'
    WHEN 'SO' THEN 'Somalia'
    WHEN 'SB' THEN 'Solomon Islands'
    WHEN 'SD' THEN 'Sudan'
    WHEN 'SR' THEN 'Suriname'
    WHEN 'LK' THEN 'Sri Lanka'
    WHEN 'SJ' THEN 'Svalbard & Jan Mayen'
    WHEN 'SE' THEN 'Sweden'
    WHEN 'CH' THEN 'Switzerland'
    WHEN 'ES' THEN 'Spain'
    WHEN 'SK' THEN 'Slovakia'
    WHEN 'SI' THEN 'Slovenia'
    WHEN 'SY' THEN 'Syria'
    WHEN 'SL' THEN 'Sierra Leone'
    WHEN 'SX' THEN 'Sint Maarten'
    WHEN 'SG' THEN 'Singapore'
    WHEN 'AE' THEN 'United Arab Emirates'
    WHEN 'AW' THEN 'Aruba'
    WHEN 'AM' THEN 'Armenia'
    WHEN 'AR' THEN 'Argentina'
    WHEN 'AS' THEN 'American Samoa'
    WHEN 'IS' THEN 'Iceland'
    WHEN 'HT' THEN 'Haiti'
    WHEN 'IE' THEN 'Ireland'
    WHEN 'AZ' THEN 'Azerbaijan'
    WHEN 'AF' THEN 'Afghanistan'
    WHEN 'AD' THEN 'Andorra'
    WHEN 'AL' THEN 'Albania'
    WHEN 'DZ' THEN 'Algeria'
    WHEN 'AO' THEN 'Angola'
    WHEN 'AG' THEN 'Antigua & Barbuda'
    WHEN 'AI' THEN 'Anguilla'
    WHEN 'ER' THEN 'Eritrea'
    WHEN 'SZ' THEN 'Eswatini'
    WHEN 'EE' THEN 'Estonia'
    WHEN 'EC' THEN 'Ecuador'
    WHEN 'ET' THEN 'Ethiopia'
    WHEN 'SV' THEN 'El Salvador'
    WHEN 'GB' THEN 'United Kingdom'
    WHEN 'VG' THEN 'British Virgin Islands'
    WHEN 'IO' THEN 'British Indian Ocean Territory'
    WHEN 'YE' THEN 'Yemen'
    WHEN 'OM' THEN 'Oman'
    WHEN 'AU' THEN 'Australia'
    WHEN 'AT' THEN 'Austria'
    WHEN 'HN' THEN 'Honduras'
    WHEN 'AX' THEN 'Åland Islands'
    WHEN 'WF' THEN 'Wallis & Futuna'
    WHEN 'JO' THEN 'Jordan'
    WHEN 'UG' THEN 'Uganda'
    WHEN 'UY' THEN 'Uruguay'
    WHEN 'UZ' THEN 'Uzbekistan'
    WHEN 'UA' THEN 'Ukraine'
    WHEN 'IQ' THEN 'Iraq'
    WHEN 'IR' THEN 'Iran'
    WHEN 'IL' THEN 'Israel'
    WHEN 'EG' THEN 'Egypt'
    WHEN 'IT' THEN 'Italy'
    WHEN 'IN' THEN 'India'
    WHEN 'ID' THEN 'Indonesia'
    WHEN 'JP' THEN 'Japan'
    WHEN 'JM' THEN 'Jamaica'
    WHEN 'ZM' THEN 'Zambia'
    WHEN 'JE' THEN 'Jersey'
    WHEN 'GQ' THEN 'Equatorial Guinea'
    WHEN 'GE' THEN 'Georgia'
    WHEN 'CN' THEN 'China'
    WHEN 'CF' THEN 'Central African Republic'
    WHEN 'DJ' THEN 'Djibouti'
    WHEN 'GI' THEN 'Gibraltar'
    WHEN 'ZW' THEN 'Zimbabwe'
    WHEN 'TD' THEN 'Chad'
    WHEN 'CZ' THEN 'Czechia'
    WHEN 'CL' THEN 'Chile'
    WHEN 'CM' THEN 'Cameroon'
    WHEN 'CV' THEN 'Cape Verde'
    WHEN 'KZ' THEN 'Kazakhstan'
    WHEN 'QA' THEN 'Qatar'
    WHEN 'KH' THEN 'Cambodia'
    WHEN 'CA' THEN 'Canada'
    WHEN 'KE' THEN 'Kenya'
    WHEN 'KY' THEN 'Cayman Islands'
    WHEN 'KM' THEN 'Comoros'
    WHEN 'CR' THEN 'Costa Rica'
    WHEN 'CC' THEN 'Cocos (Keeling) Islands'
    WHEN 'CI' THEN 'Côte d''Ivoire'
    WHEN 'CO' THEN 'Colombia'
    WHEN 'CG' THEN 'Congo - Brazzaville'
    WHEN 'CD' THEN 'Congo - Kinshasa'
    WHEN 'CU' THEN 'Cuba'
    WHEN 'KW' THEN 'Kuwait'
    WHEN 'CK' THEN 'Cook Islands'
    WHEN 'CW' THEN 'Curaçao'
    WHEN 'HR' THEN 'Croatia'
    WHEN 'CX' THEN 'Christmas Island'
    WHEN 'KG' THEN 'Kyrgyzstan'
    WHEN 'KI' THEN 'Kiribati'
    WHEN 'CY' THEN 'Cyprus'
    WHEN 'TJ' THEN 'Tajikistan'
    WHEN 'TZ' THEN 'Tanzania'
    WHEN 'TH' THEN 'Thailand'
    WHEN 'TC' THEN 'Turks & Caicos Islands'
    WHEN 'TR' THEN 'Turkey'
    WHEN 'TG' THEN 'Togo'
    WHEN 'TK' THEN 'Tokelau'
    WHEN 'TO' THEN 'Tonga'
    WHEN 'TM' THEN 'Turkmenistan'
    WHEN 'TV' THEN 'Tuvalu'
    WHEN 'TN' THEN 'Tunisia'
    WHEN 'TT' THEN 'Trinidad & Tobago'
    WHEN 'PA' THEN 'Panama'
    WHEN 'PY' THEN 'Paraguay'
    WHEN 'PK' THEN 'Pakistan'
    WHEN 'PG' THEN 'Papua New Guinea'
    WHEN 'PW' THEN 'Palau'
    WHEN 'PS' THEN 'Palestinian Territories'
    WHEN 'FO' THEN 'Faroe Islands'
    WHEN 'PE' THEN 'Peru'
    WHEN 'PT' THEN 'Portugal'
    WHEN 'FK' THEN 'Falkland Islands'
    WHEN 'PL' THEN 'Poland'
    WHEN 'PR' THEN 'Puerto Rico'
    WHEN 'TF' THEN 'French Southern Territories'
    WHEN 'FR' THEN 'France'
    WHEN 'GF' THEN 'French Guiana'
    WHEN 'PF' THEN 'French Polynesia'
    WHEN 'FJ' THEN 'Fiji'
    WHEN 'FI' THEN 'Finland'
    WHEN 'PH' THEN 'Philippines'
    WHEN 'PN' THEN 'Pitcairn Islands'
    WHEN 'HM' THEN 'Heard & McDonald Islands'
    WHEN 'HU' THEN 'Hungary'
    WHEN 'HK' THEN 'Hong Kong SAR China'
    ELSE english_name
END;
